name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: website

      - name: Run ESLint
        run: npm run lint
        working-directory: website

      - name: Run TypeScript check
        run: npm run type-check
        working-directory: website

      - name: Build project
        run: npm run build
        working-directory: website

      - name: Run security audit
        run: npm audit --audit-level=critical
        working-directory: website

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build-artifacts
          path: website/out